# Generated by Django 5.2.9 on 2026-01-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='popgapopup',
            name='geo_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='popgapopup',
            name='geo_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
