# Generated by Django 5.2.9 on 2026-01-09 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_geo_x_place_geo_y_alter_place_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popgapopup',
            name='image_size',
        ),
    ]
