# Generated by Django 5.2.9 on 2026-01-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_popgapopup_image_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='detail_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='상세 카테고리'),
        ),
        migrations.AddField(
            model_name='place',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='상세 링크'),
        ),
    ]
