# Generated by Django 5.2.9 on 2026-01-12 07:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_place_user'),
        ('routes', '0002_alter_route_options_route_hash_key_route_is_dirty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='PopgaPopup',
        ),
        migrations.RemoveIndex(
            model_name='placevisit',
            name='places_plac_place_i_91c52a_idx',
        ),
        migrations.AlterUniqueTogether(
            name='placelike',
            unique_together={('user', 'place')},
        ),
        migrations.RemoveField(
            model_name='placevisit',
            name='popup_id',
        ),
        migrations.AddField(
            model_name='place',
            name='geo_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='image_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='popup_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='placevisit',
            index=models.Index(fields=['place', 'visited_at'], name='places_plac_place_i_f9e169_idx'),
        ),
        migrations.RemoveField(
            model_name='placelike',
            name='popup_id',
        ),
    ]
