# Generated by Django 5.2.9 on 2026-01-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_delete_popgapopup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='popup_date',
        ),
        migrations.AddField(
            model_name='place',
            name='end_date',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='start_date',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
