# Generated by Django 5.2.9 on 2026-01-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_remove_place_popup_date_place_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image_path',
        ),
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
