# Generated by Django 5.2.9 on 2026-01-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_remove_place_image_path_place_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_popup',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
