# Generated by Django 5.2.9 on 2026-01-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_place_is_popup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='is_popup',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
