services:
  django:
    build: .
    expose:
      - "8000"

    env_file:
      - .env

    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:5432/${POSTGRES_DB}

    restart: unless-stopped

    command: >
      gunicorn config.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3