# Generated by Django 5.2.9 on 2026-01-11 01:57

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='route',
            name='hash_key',
            field=models.CharField(db_index=True, default=None, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='is_dirty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route',
            name='locations_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='optimal_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=None, size=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='original_coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.gis.db.models.fields.PointField(srid=4326), default=None, size=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='route',
            name='walking_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['user', 'created_at'], name='routes_rout_user_id_97b45b_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['hash_key'], name='routes_rout_hash_ke_205483_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['walking_mode', 'locations_count'], name='routes_rout_walking_96f008_idx'),
        ),
    ]
